{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 38,
   "id": "8178af57-05ef-42ad-b15d-8c796f01bae7",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "from flask import Flask\n",
    "import openai"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "2f898b37-1f65-481c-8a8a-0237f2939211",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>zp_xVJ20</th>\n",
       "      <th>zp_xVJ20 href</th>\n",
       "      <th>zp-link href</th>\n",
       "      <th>zp_Y6y8d</th>\n",
       "      <th>zp_IL7J9 src</th>\n",
       "      <th>zp_WM8e5</th>\n",
       "      <th>zp_WM8e5 href</th>\n",
       "      <th>zp-link href 2</th>\n",
       "      <th>zp-link href 3</th>\n",
       "      <th>zp-link href 4</th>\n",
       "      <th>...</th>\n",
       "      <th>zp_yc3J_ 6</th>\n",
       "      <th>zp_yc3J_ 7</th>\n",
       "      <th>zp_yc3J_ 8</th>\n",
       "      <th>zp_yc3J_ 9</th>\n",
       "      <th>zp_yc3J_ 10</th>\n",
       "      <th>zp_yc3J_ 11</th>\n",
       "      <th>zp_yc3J_ 12</th>\n",
       "      <th>zp_yc3J_ 13</th>\n",
       "      <th>zp_yc3J_ 14</th>\n",
       "      <th>zp_lm1kV</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Suzanne Swann</td>\n",
       "      <td>https://app.apollo.io/#/contacts/64f40154e5ec1...</td>\n",
       "      <td>http://www.linkedin.com/in/suzanne-swann-0b326b13</td>\n",
       "      <td>Director, Specialty Care Operations &amp; Strategy</td>\n",
       "      <td>https://zenprospect-production.s3.amazonaws.co...</td>\n",
       "      <td>The Southeast Permanente Medical Group</td>\n",
       "      <td>https://app.apollo.io/#/accounts/64f40156e5ec1...</td>\n",
       "      <td>http://www.tspmg.com/</td>\n",
       "      <td>http://www.linkedin.com/company/tspmg</td>\n",
       "      <td>https://facebook.com/The-Southeast-Permanente-...</td>\n",
       "      <td>...</td>\n",
       "      <td>gastroenterology,</td>\n",
       "      <td>neurology,</td>\n",
       "      <td>ophthalmology,</td>\n",
       "      <td>psychiatry,</td>\n",
       "      <td>pulmonology,</td>\n",
       "      <td>rheumatology,</td>\n",
       "      <td>radiology,</td>\n",
       "      <td>surgery,</td>\n",
       "      <td>urology,</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Paul Scott</td>\n",
       "      <td>https://app.apollo.io/#/contacts/64f40154e5ec1...</td>\n",
       "      <td>http://www.linkedin.com/in/paul-scott-md-facs-...</td>\n",
       "      <td>President and General Surgeon</td>\n",
       "      <td>https://zenprospect-production.s3.amazonaws.co...</td>\n",
       "      <td>Hudson Physicians</td>\n",
       "      <td>https://app.apollo.io/#/accounts/64f40156e5ec1...</td>\n",
       "      <td>http://www.hudsonphysicians.com/</td>\n",
       "      <td>http://www.linkedin.com/company/hudson-physicians</td>\n",
       "      <td>https://www.facebook.com/HudsonPhysicians/</td>\n",
       "      <td>...</td>\n",
       "      <td>gynecology,</td>\n",
       "      <td>general surgery,</td>\n",
       "      <td>allergy,</td>\n",
       "      <td>immunization clinic,</td>\n",
       "      <td>cosmetic services,</td>\n",
       "      <td>occupational medicine,</td>\n",
       "      <td>personal lab services,</td>\n",
       "      <td>diabetes education,</td>\n",
       "      <td>nurse midwifery,</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Ciera McNeal</td>\n",
       "      <td>https://app.apollo.io/#/contacts/64f40154e5ec1...</td>\n",
       "      <td>http://www.linkedin.com/in/ciera-mcneal-089b45166</td>\n",
       "      <td>Human Resources Director of Talent and Culture</td>\n",
       "      <td>https://zenprospect-production.s3.amazonaws.co...</td>\n",
       "      <td>Josselyn</td>\n",
       "      <td>https://app.apollo.io/#/accounts/64f40156e5ec1...</td>\n",
       "      <td>http://www.josselyn.org/</td>\n",
       "      <td>http://www.linkedin.com/company/josselyn</td>\n",
       "      <td>https://www.facebook.com/josselyncenter/</td>\n",
       "      <td>...</td>\n",
       "      <td>counseling &amp; mental health,</td>\n",
       "      <td>health &amp; medical</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Amy Jarman</td>\n",
       "      <td>https://app.apollo.io/#/contacts/64f40154e5ec1...</td>\n",
       "      <td>http://www.linkedin.com/in/amy-jarman-6b901246</td>\n",
       "      <td>Head of Human Resources</td>\n",
       "      <td>https://zenprospect-production.s3.amazonaws.co...</td>\n",
       "      <td>Hearing Care Solutions</td>\n",
       "      <td>https://app.apollo.io/#/accounts/64f40156e5ec1...</td>\n",
       "      <td>http://www.hearingcaresolutions.com/</td>\n",
       "      <td>http://www.linkedin.com/company/hearingcaresol...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Todd Zulauf</td>\n",
       "      <td>https://app.apollo.io/#/contacts/64f40154e5ec1...</td>\n",
       "      <td>http://www.linkedin.com/in/toddzulauf</td>\n",
       "      <td>Director of Information Technology</td>\n",
       "      <td>https://zenprospect-production.s3.amazonaws.co...</td>\n",
       "      <td>Alvarado Parkway Institute Behavioral Health S...</td>\n",
       "      <td>https://app.apollo.io/#/accounts/64f40156e5ec1...</td>\n",
       "      <td>http://www.apibhs.com/</td>\n",
       "      <td>http://www.linkedin.com/company/alvaradoparkwa...</td>\n",
       "      <td>https://www.facebook.com/AlvaradoParkwayInstit...</td>\n",
       "      <td>...</td>\n",
       "      <td>psychiatric nursing,</td>\n",
       "      <td>social services,</td>\n",
       "      <td>inpatient care,</td>\n",
       "      <td>outpatient care,</td>\n",
       "      <td>path,</td>\n",
       "      <td>assessment services,</td>\n",
       "      <td>psychotherapy,</td>\n",
       "      <td>substance abuse,</td>\n",
       "      <td>transportation,</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 30 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "        zp_xVJ20                                      zp_xVJ20 href  \\\n",
       "0  Suzanne Swann  https://app.apollo.io/#/contacts/64f40154e5ec1...   \n",
       "1     Paul Scott  https://app.apollo.io/#/contacts/64f40154e5ec1...   \n",
       "2   Ciera McNeal  https://app.apollo.io/#/contacts/64f40154e5ec1...   \n",
       "3     Amy Jarman  https://app.apollo.io/#/contacts/64f40154e5ec1...   \n",
       "4    Todd Zulauf  https://app.apollo.io/#/contacts/64f40154e5ec1...   \n",
       "\n",
       "                                        zp-link href  \\\n",
       "0  http://www.linkedin.com/in/suzanne-swann-0b326b13   \n",
       "1  http://www.linkedin.com/in/paul-scott-md-facs-...   \n",
       "2  http://www.linkedin.com/in/ciera-mcneal-089b45166   \n",
       "3     http://www.linkedin.com/in/amy-jarman-6b901246   \n",
       "4              http://www.linkedin.com/in/toddzulauf   \n",
       "\n",
       "                                         zp_Y6y8d  \\\n",
       "0  Director, Specialty Care Operations & Strategy   \n",
       "1                   President and General Surgeon   \n",
       "2  Human Resources Director of Talent and Culture   \n",
       "3                         Head of Human Resources   \n",
       "4              Director of Information Technology   \n",
       "\n",
       "                                        zp_IL7J9 src  \\\n",
       "0  https://zenprospect-production.s3.amazonaws.co...   \n",
       "1  https://zenprospect-production.s3.amazonaws.co...   \n",
       "2  https://zenprospect-production.s3.amazonaws.co...   \n",
       "3  https://zenprospect-production.s3.amazonaws.co...   \n",
       "4  https://zenprospect-production.s3.amazonaws.co...   \n",
       "\n",
       "                                            zp_WM8e5  \\\n",
       "0             The Southeast Permanente Medical Group   \n",
       "1                                  Hudson Physicians   \n",
       "2                                           Josselyn   \n",
       "3                             Hearing Care Solutions   \n",
       "4  Alvarado Parkway Institute Behavioral Health S...   \n",
       "\n",
       "                                       zp_WM8e5 href  \\\n",
       "0  https://app.apollo.io/#/accounts/64f40156e5ec1...   \n",
       "1  https://app.apollo.io/#/accounts/64f40156e5ec1...   \n",
       "2  https://app.apollo.io/#/accounts/64f40156e5ec1...   \n",
       "3  https://app.apollo.io/#/accounts/64f40156e5ec1...   \n",
       "4  https://app.apollo.io/#/accounts/64f40156e5ec1...   \n",
       "\n",
       "                         zp-link href 2  \\\n",
       "0                 http://www.tspmg.com/   \n",
       "1      http://www.hudsonphysicians.com/   \n",
       "2              http://www.josselyn.org/   \n",
       "3  http://www.hearingcaresolutions.com/   \n",
       "4                http://www.apibhs.com/   \n",
       "\n",
       "                                      zp-link href 3  \\\n",
       "0              http://www.linkedin.com/company/tspmg   \n",
       "1  http://www.linkedin.com/company/hudson-physicians   \n",
       "2           http://www.linkedin.com/company/josselyn   \n",
       "3  http://www.linkedin.com/company/hearingcaresol...   \n",
       "4  http://www.linkedin.com/company/alvaradoparkwa...   \n",
       "\n",
       "                                      zp-link href 4  ...  \\\n",
       "0  https://facebook.com/The-Southeast-Permanente-...  ...   \n",
       "1         https://www.facebook.com/HudsonPhysicians/  ...   \n",
       "2           https://www.facebook.com/josselyncenter/  ...   \n",
       "3                                                NaN  ...   \n",
       "4  https://www.facebook.com/AlvaradoParkwayInstit...  ...   \n",
       "\n",
       "                    zp_yc3J_ 6        zp_yc3J_ 7       zp_yc3J_ 8  \\\n",
       "0            gastroenterology,        neurology,   ophthalmology,   \n",
       "1                  gynecology,  general surgery,         allergy,   \n",
       "2  counseling & mental health,  health & medical              NaN   \n",
       "3                          NaN               NaN              NaN   \n",
       "4         psychiatric nursing,  social services,  inpatient care,   \n",
       "\n",
       "             zp_yc3J_ 9         zp_yc3J_ 10             zp_yc3J_ 11  \\\n",
       "0           psychiatry,        pulmonology,           rheumatology,   \n",
       "1  immunization clinic,  cosmetic services,  occupational medicine,   \n",
       "2                   NaN                 NaN                     NaN   \n",
       "3                   NaN                 NaN                     NaN   \n",
       "4      outpatient care,               path,    assessment services,   \n",
       "\n",
       "              zp_yc3J_ 12          zp_yc3J_ 13       zp_yc3J_ 14 zp_lm1kV  \n",
       "0              radiology,             surgery,          urology,      NaN  \n",
       "1  personal lab services,  diabetes education,  nurse midwifery,      NaN  \n",
       "2                     NaN                  NaN               NaN      NaN  \n",
       "3                     NaN                  NaN               NaN      NaN  \n",
       "4          psychotherapy,     substance abuse,   transportation,      NaN  \n",
       "\n",
       "[5 rows x 30 columns]"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data = pd.read_csv(\"names.csv\")\n",
    "\n",
    "data.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "id": "0b38b828-1a84-4e60-acc9-41c69eadaa4e",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Name</th>\n",
       "      <th>Apollo Link</th>\n",
       "      <th>Owner LinkedIn</th>\n",
       "      <th>Role</th>\n",
       "      <th>Logo</th>\n",
       "      <th>Company</th>\n",
       "      <th>Owner Apollo</th>\n",
       "      <th>Website</th>\n",
       "      <th>LinkedIn</th>\n",
       "      <th>Facebook</th>\n",
       "      <th>...</th>\n",
       "      <th>Data 7</th>\n",
       "      <th>Data 8</th>\n",
       "      <th>Data 9</th>\n",
       "      <th>Data 10</th>\n",
       "      <th>Data 11</th>\n",
       "      <th>Data 12</th>\n",
       "      <th>Data 13</th>\n",
       "      <th>Data 14</th>\n",
       "      <th>Data 15</th>\n",
       "      <th>Data 16</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Suzanne Swann</td>\n",
       "      <td>https://app.apollo.io/#/contacts/64f40154e5ec1...</td>\n",
       "      <td>http://www.linkedin.com/in/suzanne-swann-0b326b13</td>\n",
       "      <td>Director, Specialty Care Operations &amp; Strategy</td>\n",
       "      <td>https://zenprospect-production.s3.amazonaws.co...</td>\n",
       "      <td>The Southeast Permanente Medical Group</td>\n",
       "      <td>https://app.apollo.io/#/accounts/64f40156e5ec1...</td>\n",
       "      <td>http://www.tspmg.com/</td>\n",
       "      <td>http://www.linkedin.com/company/tspmg</td>\n",
       "      <td>https://facebook.com/The-Southeast-Permanente-...</td>\n",
       "      <td>...</td>\n",
       "      <td>gastroenterology,</td>\n",
       "      <td>neurology,</td>\n",
       "      <td>ophthalmology,</td>\n",
       "      <td>psychiatry,</td>\n",
       "      <td>pulmonology,</td>\n",
       "      <td>rheumatology,</td>\n",
       "      <td>radiology,</td>\n",
       "      <td>surgery,</td>\n",
       "      <td>urology,</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Paul Scott</td>\n",
       "      <td>https://app.apollo.io/#/contacts/64f40154e5ec1...</td>\n",
       "      <td>http://www.linkedin.com/in/paul-scott-md-facs-...</td>\n",
       "      <td>President and General Surgeon</td>\n",
       "      <td>https://zenprospect-production.s3.amazonaws.co...</td>\n",
       "      <td>Hudson Physicians</td>\n",
       "      <td>https://app.apollo.io/#/accounts/64f40156e5ec1...</td>\n",
       "      <td>http://www.hudsonphysicians.com/</td>\n",
       "      <td>http://www.linkedin.com/company/hudson-physicians</td>\n",
       "      <td>https://www.facebook.com/HudsonPhysicians/</td>\n",
       "      <td>...</td>\n",
       "      <td>gynecology,</td>\n",
       "      <td>general surgery,</td>\n",
       "      <td>allergy,</td>\n",
       "      <td>immunization clinic,</td>\n",
       "      <td>cosmetic services,</td>\n",
       "      <td>occupational medicine,</td>\n",
       "      <td>personal lab services,</td>\n",
       "      <td>diabetes education,</td>\n",
       "      <td>nurse midwifery,</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Ciera McNeal</td>\n",
       "      <td>https://app.apollo.io/#/contacts/64f40154e5ec1...</td>\n",
       "      <td>http://www.linkedin.com/in/ciera-mcneal-089b45166</td>\n",
       "      <td>Human Resources Director of Talent and Culture</td>\n",
       "      <td>https://zenprospect-production.s3.amazonaws.co...</td>\n",
       "      <td>Josselyn</td>\n",
       "      <td>https://app.apollo.io/#/accounts/64f40156e5ec1...</td>\n",
       "      <td>http://www.josselyn.org/</td>\n",
       "      <td>http://www.linkedin.com/company/josselyn</td>\n",
       "      <td>https://www.facebook.com/josselyncenter/</td>\n",
       "      <td>...</td>\n",
       "      <td>counseling &amp; mental health,</td>\n",
       "      <td>health &amp; medical</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Amy Jarman</td>\n",
       "      <td>https://app.apollo.io/#/contacts/64f40154e5ec1...</td>\n",
       "      <td>http://www.linkedin.com/in/amy-jarman-6b901246</td>\n",
       "      <td>Head of Human Resources</td>\n",
       "      <td>https://zenprospect-production.s3.amazonaws.co...</td>\n",
       "      <td>Hearing Care Solutions</td>\n",
       "      <td>https://app.apollo.io/#/accounts/64f40156e5ec1...</td>\n",
       "      <td>http://www.hearingcaresolutions.com/</td>\n",
       "      <td>http://www.linkedin.com/company/hearingcaresol...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Todd Zulauf</td>\n",
       "      <td>https://app.apollo.io/#/contacts/64f40154e5ec1...</td>\n",
       "      <td>http://www.linkedin.com/in/toddzulauf</td>\n",
       "      <td>Director of Information Technology</td>\n",
       "      <td>https://zenprospect-production.s3.amazonaws.co...</td>\n",
       "      <td>Alvarado Parkway Institute Behavioral Health S...</td>\n",
       "      <td>https://app.apollo.io/#/accounts/64f40156e5ec1...</td>\n",
       "      <td>http://www.apibhs.com/</td>\n",
       "      <td>http://www.linkedin.com/company/alvaradoparkwa...</td>\n",
       "      <td>https://www.facebook.com/AlvaradoParkwayInstit...</td>\n",
       "      <td>...</td>\n",
       "      <td>psychiatric nursing,</td>\n",
       "      <td>social services,</td>\n",
       "      <td>inpatient care,</td>\n",
       "      <td>outpatient care,</td>\n",
       "      <td>path,</td>\n",
       "      <td>assessment services,</td>\n",
       "      <td>psychotherapy,</td>\n",
       "      <td>substance abuse,</td>\n",
       "      <td>transportation,</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>488</th>\n",
       "      <td>Marilyn Derry</td>\n",
       "      <td>https://app.apollo.io/#/contacts/64f40154e5ec1...</td>\n",
       "      <td>http://www.linkedin.com/in/marilyn-derry-3663a218</td>\n",
       "      <td>Director, Food/Nutrition Services</td>\n",
       "      <td>https://zenprospect-production.s3.amazonaws.co...</td>\n",
       "      <td>McDonough District Hospital</td>\n",
       "      <td>https://app.apollo.io/#/accounts/64f40156e5ec1...</td>\n",
       "      <td>http://www.mdh.org/</td>\n",
       "      <td>http://www.linkedin.com/company/mcdonough-dist...</td>\n",
       "      <td>https://www.facebook.com/McDonough.District.Ho...</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>489</th>\n",
       "      <td>Bradley Gatian</td>\n",
       "      <td>https://app.apollo.io/#/contacts/64f40154e5ec1...</td>\n",
       "      <td>http://www.linkedin.com/in/bradley-gatian-3828...</td>\n",
       "      <td>Director Of Facilities Management</td>\n",
       "      <td>https://zenprospect-production.s3.amazonaws.co...</td>\n",
       "      <td>Avow Hospice, Inc.</td>\n",
       "      <td>https://app.apollo.io/#/accounts/64f40156e5ec1...</td>\n",
       "      <td>http://www.avowcares.org/</td>\n",
       "      <td>http://www.linkedin.com/company/avowcares</td>\n",
       "      <td>https://www.facebook.com/avowcares</td>\n",
       "      <td>...</td>\n",
       "      <td>childrens grief support,</td>\n",
       "      <td>palliative care,</td>\n",
       "      <td>community service/non-profit,</td>\n",
       "      <td>health &amp; medical,</td>\n",
       "      <td>hospice,</td>\n",
       "      <td>local services</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>490</th>\n",
       "      <td>Lenna Samander</td>\n",
       "      <td>https://app.apollo.io/#/contacts/64f40154e5ec1...</td>\n",
       "      <td>http://www.linkedin.com/in/lsamander</td>\n",
       "      <td>Senior Director Human Resources</td>\n",
       "      <td>https://zenprospect-production.s3.amazonaws.co...</td>\n",
       "      <td>United Medical Imaging</td>\n",
       "      <td>https://app.apollo.io/#/accounts/64f40156e5ec1...</td>\n",
       "      <td>http://www.umih.com/</td>\n",
       "      <td>http://www.linkedin.com/company/united-medical...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>491</th>\n",
       "      <td>John Mulder</td>\n",
       "      <td>https://app.apollo.io/#/contacts/64f40154e5ec1...</td>\n",
       "      <td>http://www.linkedin.com/in/john-mulder-33a85766</td>\n",
       "      <td>Director Of Maintenance</td>\n",
       "      <td>https://zenprospect-production.s3.amazonaws.co...</td>\n",
       "      <td>Omega Senior Living</td>\n",
       "      <td>https://app.apollo.io/#/accounts/64f40156e5ec1...</td>\n",
       "      <td>http://www.omegasrliving.com/</td>\n",
       "      <td>http://www.linkedin.com/company/omega-senior-l...</td>\n",
       "      <td>https://www.facebook.com/OmegaSeniorLiving/</td>\n",
       "      <td>...</td>\n",
       "      <td>senior living reposition consulting services,</td>\n",
       "      <td>leaseups consulting services,</td>\n",
       "      <td>receivership management,</td>\n",
       "      <td>development consulting services,</td>\n",
       "      <td>assisted living management,</td>\n",
       "      <td>memory care management,</td>\n",
       "      <td>independent living management,</td>\n",
       "      <td>skilled nursing management,</td>\n",
       "      <td>foreclosure management</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>492</th>\n",
       "      <td>Justin Shepherd</td>\n",
       "      <td>https://app.apollo.io/#/contacts/64f40154e5ec1...</td>\n",
       "      <td>http://www.linkedin.com/in/justin-shepherd-pt-...</td>\n",
       "      <td>VP of Operations</td>\n",
       "      <td>https://zenprospect-production.s3.amazonaws.co...</td>\n",
       "      <td>ErgoScience, Inc.</td>\n",
       "      <td>https://app.apollo.io/#/accounts/64f40156e5ec1...</td>\n",
       "      <td>http://www.ergoscience.com/</td>\n",
       "      <td>http://www.linkedin.com/company/ergoscience</td>\n",
       "      <td>https://facebook.com/pages/ErgoScience,+Inc./9...</td>\n",
       "      <td>...</td>\n",
       "      <td>employee training,</td>\n",
       "      <td>fit for duty screening,</td>\n",
       "      <td>worksite rehabilitation,</td>\n",
       "      <td>functional capacity evaluation</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>493 rows × 30 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                Name                                        Apollo Link  \\\n",
       "0      Suzanne Swann  https://app.apollo.io/#/contacts/64f40154e5ec1...   \n",
       "1         Paul Scott  https://app.apollo.io/#/contacts/64f40154e5ec1...   \n",
       "2       Ciera McNeal  https://app.apollo.io/#/contacts/64f40154e5ec1...   \n",
       "3         Amy Jarman  https://app.apollo.io/#/contacts/64f40154e5ec1...   \n",
       "4        Todd Zulauf  https://app.apollo.io/#/contacts/64f40154e5ec1...   \n",
       "..               ...                                                ...   \n",
       "488    Marilyn Derry  https://app.apollo.io/#/contacts/64f40154e5ec1...   \n",
       "489   Bradley Gatian  https://app.apollo.io/#/contacts/64f40154e5ec1...   \n",
       "490   Lenna Samander  https://app.apollo.io/#/contacts/64f40154e5ec1...   \n",
       "491      John Mulder  https://app.apollo.io/#/contacts/64f40154e5ec1...   \n",
       "492  Justin Shepherd  https://app.apollo.io/#/contacts/64f40154e5ec1...   \n",
       "\n",
       "                                        Owner LinkedIn  \\\n",
       "0    http://www.linkedin.com/in/suzanne-swann-0b326b13   \n",
       "1    http://www.linkedin.com/in/paul-scott-md-facs-...   \n",
       "2    http://www.linkedin.com/in/ciera-mcneal-089b45166   \n",
       "3       http://www.linkedin.com/in/amy-jarman-6b901246   \n",
       "4                http://www.linkedin.com/in/toddzulauf   \n",
       "..                                                 ...   \n",
       "488  http://www.linkedin.com/in/marilyn-derry-3663a218   \n",
       "489  http://www.linkedin.com/in/bradley-gatian-3828...   \n",
       "490               http://www.linkedin.com/in/lsamander   \n",
       "491    http://www.linkedin.com/in/john-mulder-33a85766   \n",
       "492  http://www.linkedin.com/in/justin-shepherd-pt-...   \n",
       "\n",
       "                                               Role  \\\n",
       "0    Director, Specialty Care Operations & Strategy   \n",
       "1                     President and General Surgeon   \n",
       "2    Human Resources Director of Talent and Culture   \n",
       "3                           Head of Human Resources   \n",
       "4                Director of Information Technology   \n",
       "..                                              ...   \n",
       "488               Director, Food/Nutrition Services   \n",
       "489               Director Of Facilities Management   \n",
       "490                 Senior Director Human Resources   \n",
       "491                         Director Of Maintenance   \n",
       "492                                VP of Operations   \n",
       "\n",
       "                                                  Logo  \\\n",
       "0    https://zenprospect-production.s3.amazonaws.co...   \n",
       "1    https://zenprospect-production.s3.amazonaws.co...   \n",
       "2    https://zenprospect-production.s3.amazonaws.co...   \n",
       "3    https://zenprospect-production.s3.amazonaws.co...   \n",
       "4    https://zenprospect-production.s3.amazonaws.co...   \n",
       "..                                                 ...   \n",
       "488  https://zenprospect-production.s3.amazonaws.co...   \n",
       "489  https://zenprospect-production.s3.amazonaws.co...   \n",
       "490  https://zenprospect-production.s3.amazonaws.co...   \n",
       "491  https://zenprospect-production.s3.amazonaws.co...   \n",
       "492  https://zenprospect-production.s3.amazonaws.co...   \n",
       "\n",
       "                                               Company  \\\n",
       "0               The Southeast Permanente Medical Group   \n",
       "1                                    Hudson Physicians   \n",
       "2                                             Josselyn   \n",
       "3                               Hearing Care Solutions   \n",
       "4    Alvarado Parkway Institute Behavioral Health S...   \n",
       "..                                                 ...   \n",
       "488                        McDonough District Hospital   \n",
       "489                                 Avow Hospice, Inc.   \n",
       "490                             United Medical Imaging   \n",
       "491                                Omega Senior Living   \n",
       "492                                  ErgoScience, Inc.   \n",
       "\n",
       "                                          Owner Apollo  \\\n",
       "0    https://app.apollo.io/#/accounts/64f40156e5ec1...   \n",
       "1    https://app.apollo.io/#/accounts/64f40156e5ec1...   \n",
       "2    https://app.apollo.io/#/accounts/64f40156e5ec1...   \n",
       "3    https://app.apollo.io/#/accounts/64f40156e5ec1...   \n",
       "4    https://app.apollo.io/#/accounts/64f40156e5ec1...   \n",
       "..                                                 ...   \n",
       "488  https://app.apollo.io/#/accounts/64f40156e5ec1...   \n",
       "489  https://app.apollo.io/#/accounts/64f40156e5ec1...   \n",
       "490  https://app.apollo.io/#/accounts/64f40156e5ec1...   \n",
       "491  https://app.apollo.io/#/accounts/64f40156e5ec1...   \n",
       "492  https://app.apollo.io/#/accounts/64f40156e5ec1...   \n",
       "\n",
       "                                  Website  \\\n",
       "0                   http://www.tspmg.com/   \n",
       "1        http://www.hudsonphysicians.com/   \n",
       "2                http://www.josselyn.org/   \n",
       "3    http://www.hearingcaresolutions.com/   \n",
       "4                  http://www.apibhs.com/   \n",
       "..                                    ...   \n",
       "488                   http://www.mdh.org/   \n",
       "489             http://www.avowcares.org/   \n",
       "490                  http://www.umih.com/   \n",
       "491         http://www.omegasrliving.com/   \n",
       "492           http://www.ergoscience.com/   \n",
       "\n",
       "                                              LinkedIn  \\\n",
       "0                http://www.linkedin.com/company/tspmg   \n",
       "1    http://www.linkedin.com/company/hudson-physicians   \n",
       "2             http://www.linkedin.com/company/josselyn   \n",
       "3    http://www.linkedin.com/company/hearingcaresol...   \n",
       "4    http://www.linkedin.com/company/alvaradoparkwa...   \n",
       "..                                                 ...   \n",
       "488  http://www.linkedin.com/company/mcdonough-dist...   \n",
       "489          http://www.linkedin.com/company/avowcares   \n",
       "490  http://www.linkedin.com/company/united-medical...   \n",
       "491  http://www.linkedin.com/company/omega-senior-l...   \n",
       "492        http://www.linkedin.com/company/ergoscience   \n",
       "\n",
       "                                              Facebook  ...  \\\n",
       "0    https://facebook.com/The-Southeast-Permanente-...  ...   \n",
       "1           https://www.facebook.com/HudsonPhysicians/  ...   \n",
       "2             https://www.facebook.com/josselyncenter/  ...   \n",
       "3                                                  NaN  ...   \n",
       "4    https://www.facebook.com/AlvaradoParkwayInstit...  ...   \n",
       "..                                                 ...  ...   \n",
       "488  https://www.facebook.com/McDonough.District.Ho...  ...   \n",
       "489                 https://www.facebook.com/avowcares  ...   \n",
       "490                                                NaN  ...   \n",
       "491        https://www.facebook.com/OmegaSeniorLiving/  ...   \n",
       "492  https://facebook.com/pages/ErgoScience,+Inc./9...  ...   \n",
       "\n",
       "                                            Data 7  \\\n",
       "0                                gastroenterology,   \n",
       "1                                      gynecology,   \n",
       "2                      counseling & mental health,   \n",
       "3                                              NaN   \n",
       "4                             psychiatric nursing,   \n",
       "..                                             ...   \n",
       "488                                            NaN   \n",
       "489                       childrens grief support,   \n",
       "490                                            NaN   \n",
       "491  senior living reposition consulting services,   \n",
       "492                             employee training,   \n",
       "\n",
       "                            Data 8                         Data 9  \\\n",
       "0                       neurology,                 ophthalmology,   \n",
       "1                 general surgery,                       allergy,   \n",
       "2                 health & medical                            NaN   \n",
       "3                              NaN                            NaN   \n",
       "4                 social services,                inpatient care,   \n",
       "..                             ...                            ...   \n",
       "488                            NaN                            NaN   \n",
       "489               palliative care,  community service/non-profit,   \n",
       "490                            NaN                            NaN   \n",
       "491  leaseups consulting services,       receivership management,   \n",
       "492        fit for duty screening,       worksite rehabilitation,   \n",
       "\n",
       "                              Data 10                      Data 11  \\\n",
       "0                         psychiatry,                 pulmonology,   \n",
       "1                immunization clinic,           cosmetic services,   \n",
       "2                                 NaN                          NaN   \n",
       "3                                 NaN                          NaN   \n",
       "4                    outpatient care,                        path,   \n",
       "..                                ...                          ...   \n",
       "488                               NaN                          NaN   \n",
       "489                 health & medical,                     hospice,   \n",
       "490                               NaN                          NaN   \n",
       "491  development consulting services,  assisted living management,   \n",
       "492    functional capacity evaluation                          NaN   \n",
       "\n",
       "                     Data 12                         Data 13  \\\n",
       "0              rheumatology,                      radiology,   \n",
       "1     occupational medicine,          personal lab services,   \n",
       "2                        NaN                             NaN   \n",
       "3                        NaN                             NaN   \n",
       "4       assessment services,                  psychotherapy,   \n",
       "..                       ...                             ...   \n",
       "488                      NaN                             NaN   \n",
       "489           local services                             NaN   \n",
       "490                      NaN                             NaN   \n",
       "491  memory care management,  independent living management,   \n",
       "492                      NaN                             NaN   \n",
       "\n",
       "                         Data 14                 Data 15 Data 16  \n",
       "0                       surgery,                urology,     NaN  \n",
       "1            diabetes education,        nurse midwifery,     NaN  \n",
       "2                            NaN                     NaN     NaN  \n",
       "3                            NaN                     NaN     NaN  \n",
       "4               substance abuse,         transportation,     NaN  \n",
       "..                           ...                     ...     ...  \n",
       "488                          NaN                     NaN     NaN  \n",
       "489                          NaN                     NaN     NaN  \n",
       "490                          NaN                     NaN     NaN  \n",
       "491  skilled nursing management,  foreclosure management     NaN  \n",
       "492                          NaN                     NaN     NaN  \n",
       "\n",
       "[493 rows x 30 columns]"
      ]
     },
     "execution_count": 30,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data = data.rename(columns={'zp_xVJ20': 'Owner Name',\n",
    "                            'zp-link href': 'Owner LinkedIn',\n",
    "                            'zp_xVJ20 href': 'Apollo Link',\n",
    "                            'zp_Y6y8d 2': 'Location',\n",
    "                            'zp_Y6y8d 3': 'Number of Employees',\n",
    "                            'zp_Y6y8d': 'Role', \n",
    "                            'zp_WM8e5': 'Company Name', \n",
    "                            'zp_IL7J9 src': 'Logo', \n",
    "                            'zp-link href 2': 'Website',\n",
    "                            'zp-link href 3': 'Company LinkedIn',\n",
    "                            'zp-link href 4': 'Facebook',\n",
    "                            'zp_WM8e5 href': 'Owner Apollo',\n",
    "                            'zp-link href 5': 'Twitter',\n",
    "                            'zp-link': 'Email'\n",
    "                           })\n",
    "\n",
    "data = data.rename(columns={'zp_PHqgZ': 'Data 1',\n",
    "                            'zp_yc3J_': 'Data 2',\n",
    "                            'zp_yc3J_ 2': 'Data 3',\n",
    "                            'zp_yc3J_ 3': 'Data 4',\n",
    "                            'zp_yc3J_ 4': 'Data 5',\n",
    "                            'zp_yc3J_ 5': 'Data 6',\n",
    "                            'zp_yc3J_ 6': 'Data 7',\n",
    "                            'zp_yc3J_ 7': 'Data 8',\n",
    "                            'zp_yc3J_ 8': 'Data 9',\n",
    "                            'zp_yc3J_ 9': 'Data 10',\n",
    "                            'zp_yc3J_ 10': 'Data 11',\n",
    "                            'zp_yc3J_ 11': 'Data 12',\n",
    "                            'zp_yc3J_ 12': 'Data 13',\n",
    "                            'zp_yc3J_ 13': 'Data 14',\n",
    "                            'zp_yc3J_ 14': 'Data 15',\n",
    "                            'zp_lm1kV': 'Data 16'\n",
    "                           })\n",
    "\n",
    "\n",
    "\n",
    "data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "id": "efd17289-4bde-43a5-b26d-50fcccd99736",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Name\n",
      "Apollo Link\n",
      "Owner LinkedIn\n",
      "Role\n",
      "Logo\n",
      "Company\n",
      "Owner Apollo\n",
      "Website\n",
      "LinkedIn\n",
      "Facebook\n",
      "Twitter\n",
      "Location\n",
      "Number of Employees\n",
      "Email\n",
      "Data 1\n",
      "Data 2\n",
      "Data 3\n",
      "Data 4\n",
      "Data 5\n",
      "Data 6\n",
      "Data 7\n",
      "Data 8\n",
      "Data 9\n",
      "Data 10\n",
      "Data 11\n",
      "Data 12\n",
      "Data 13\n",
      "Data 14\n",
      "Data 15\n",
      "Data 16\n"
     ]
    }
   ],
   "source": [
    "for row in data:\n",
    "    print(row)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "id": "973967ae-b882-45a1-9b57-726f7c6da159",
   "metadata": {},
   "outputs": [],
   "source": [
    "def openai(message): \n",
    "    messages = [ {\"role\": \"system\", \n",
    "                  \n",
    "                  \"content\": \n",
    "                  \"You are a salesman designed for outreach. The message you will recieve will outline characteristics of a potential client.\" \n",
    "                 }]\n",
    "\n",
    "    chat = openai.ChatCompletion.create( model=\"gpt-3.5-turbo\", messages=messages )\n",
    "    \n",
    "    reply = chat.choices[0].message.content\n",
    "    \n",
    "    messages.append({\"role\": \"assistant\", \"content\": reply})\n",
    "    \n",
    "    return reply"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e188164e-7537-4449-bf66-e57558509182",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app '__main__'\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[31m\u001b[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.\u001b[0m\n",
      " * Running on http://127.0.0.1:5000\n",
      "\u001b[33mPress CTRL+C to quit\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "app = Flask(__name__)\n",
    "app.run(debug=False)\n",
    "\n",
    "@app.route('/GPT3Response/rizz/', methods=['GET'])"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
